#Crie um novo arquivo chamado application.properties, copie este código e insira as credenciais do seu banco de dados.
#O aquivo application.properties está citado no arquivo .gitignore, portanto não será exposto no GitHub, preservando assim a segurança do banco de dados.

spring.application.name= insira aqui o nome do projeto

# usuario do banco
spring.datasource.username = insira aqui o nome do usuário do banco de dados

# senha do banco
spring.datasource.password = insira aqui a senha do banco de dados

# url para a base de dados
spring.datasource.url = jdbc:mariadb://localhost:insira aqui a porta do seu banco de dados/tcc?useTimezone=true&serverTimezone=UTC

# dialet
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect

# Define explicitamente o driver JDBC usado para conectar ao banco MariaDB,
# evitando falhas na detecção automática do Spring Boot.
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver