spring.application.name=projeto_tcc

# usuario do banco
spring.datasource.username = #insira aqui o nome do usuário do banco de dados

# senha do banco
spring.datasource.password = #insira aqui a senha do banco de dados

# url para a base de dados
spring.datasource.url = jdbc:mariadb://localhost:insira aqui a porta do seu banco de dados/tcc?useTimezone=true&serverTimezone=UTC

# dialet
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect

# Define explicitamente o driver JDBC usado para conectar ao banco MariaDB,
# evitando falhas na detecção automática do Spring Boot.
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver


#Erro: a configura\uFFFD\uFFFDo abaixo usava jdbs:mysql e .MySQL8Dialect, por\uFFFDm o banco que est\uFFFD sendo usado \uFFFD o MariaDB. Ap\uFFFDs a altera\uFFFD\uFFFDo, o erro foi resolvido.
# url para a base de dados
#spring.datasource.url = jdbs:mysql://localhost:/banco_de_usuarios?useTimezone=true&serverTimezone=UTC
# dialet
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#

